project:
  type: book
  output-dir: ../docs

book:
  title: "Minería de Datos"
  subtitle: "ITAM 2026"
  author: "Saúl Caballero"
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - 00_computacion.md
    - 01_ecosistema.md
    - 02_intro_ml.md
    - 03_crisp_dm.md
  open-graph: true

bibliography: references.bib

execute:
  freeze: auto
  
format:
  html:
    theme:
      light: flatly
      dark: darkly
    lang: es
    font-size: 1.1em
    number-sections: false



